CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "InventoryItems" (
    "Id" uuid NOT NULL,
    "Sku" text NOT NULL,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "QuantityOnHand" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
);

CREATE TABLE "Vendors" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Email" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
);

CREATE TABLE "InboundDocuments" (
    "Id" uuid NOT NULL,
    "FileName" text NOT NULL,
    "FileUrl" text NOT NULL,
    "Status" integer NOT NULL,
    "VendorId" uuid,
    "RawAiJson" text,
    "ConfidenceScore" numeric NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InboundDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InboundDocuments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id")
);

CREATE INDEX "IX_InboundDocuments_VendorId" ON "InboundDocuments" ("VendorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260722134536_InitialCreate', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "InboundDocuments" DROP COLUMN "RawAiJson";

ALTER TABLE "InboundDocuments" RENAME COLUMN "FileUrl" TO "FilePath";

ALTER TABLE "InboundDocuments" ALTER COLUMN "ConfidenceScore" TYPE double precision;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260723090649_AddFilePathToInboundDocument', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "Vendors" ALTER COLUMN "Email" DROP NOT NULL;

ALTER TABLE "Vendors" ALTER COLUMN "Code" DROP NOT NULL;

ALTER TABLE "Vendors" ADD "Address" text;

ALTER TABLE "Vendors" ADD "ContactPerson" text;

ALTER TABLE "Vendors" ADD "Phone" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260723125319_UpdateVendorFields', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "Vendors" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "InventoryItems" ALTER COLUMN "UnitPrice" TYPE numeric(12,2);

ALTER TABLE "InventoryItems" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "InboundDocuments" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "DisplayName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiresAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Category" text NOT NULL,
    "PayloadJson" text,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenants" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Vendors_TenantId_Email" ON "Vendors" ("TenantId", "Email");

CREATE UNIQUE INDEX "IX_InventoryItems_TenantId_Sku" ON "InventoryItems" ("TenantId", "Sku");

CREATE UNIQUE INDEX "IX_InboundDocuments_TenantId_FileName" ON "InboundDocuments" ("TenantId", "FileName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_TenantId_UserName" ON "AspNetUsers" ("TenantId", "UserName");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Tenants_Slug" ON "Tenants" ("Slug");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260724111704_QueryFilterFix', '10.0.10');

COMMIT;

START TRANSACTION;
CREATE TABLE "ExternalLinkSnapshots" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Url" text NOT NULL,
    "LastHash" text NOT NULL,
    "LastCheckedAt" timestamp with time zone NOT NULL,
    "LastPayload" text,
    CONSTRAINT "PK_ExternalLinkSnapshots" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260724112019_AddExternalLinkSnapshot', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "InboundDocuments" DROP CONSTRAINT "FK_InboundDocuments_Vendors_VendorId";

ALTER TABLE "InventoryItems" ADD "InboundDocumentId" uuid;

ALTER TABLE "InventoryItems" ADD "VendorId" uuid;

CREATE INDEX "IX_InventoryItems_InboundDocumentId" ON "InventoryItems" ("InboundDocumentId");

CREATE INDEX "IX_InventoryItems_VendorId" ON "InventoryItems" ("VendorId");

ALTER TABLE "InboundDocuments" ADD CONSTRAINT "FK_InboundDocuments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT;

ALTER TABLE "InventoryItems" ADD CONSTRAINT "FK_InventoryItems_InboundDocuments_InboundDocumentId" FOREIGN KEY ("InboundDocumentId") REFERENCES "InboundDocuments" ("Id") ON DELETE SET NULL;

ALTER TABLE "InventoryItems" ADD CONSTRAINT "FK_InventoryItems_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730082302_AddVendorInventoryRelationships', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "InboundDocuments" DROP CONSTRAINT "FK_InboundDocuments_Vendors_VendorId";

ALTER TABLE "InventoryItems" DROP CONSTRAINT "FK_InventoryItems_Vendors_VendorId";

ALTER TABLE "InboundDocuments" ADD CONSTRAINT "FK_InboundDocuments_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE SET NULL;

ALTER TABLE "InventoryItems" ADD CONSTRAINT "FK_InventoryItems_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730134804_UpdateVendorDeleteBehaviorToSetNull', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE "InventoryItems" DROP CONSTRAINT "FK_InventoryItems_InboundDocuments_InboundDocumentId";

ALTER TABLE "InventoryItems" DROP CONSTRAINT "FK_InventoryItems_Vendors_VendorId";

ALTER TABLE "InventoryItems" DROP CONSTRAINT "PK_InventoryItems";

ALTER TABLE "InventoryItems" RENAME TO inventory_items;

ALTER TABLE inventory_items RENAME COLUMN "Sku" TO sku;

ALTER TABLE inventory_items RENAME COLUMN "Name" TO name;

ALTER TABLE inventory_items RENAME COLUMN "Category" TO category;

ALTER TABLE inventory_items RENAME COLUMN "Id" TO id;

ALTER TABLE inventory_items RENAME COLUMN "VendorId" TO vendor_id;

ALTER TABLE inventory_items RENAME COLUMN "UpdatedAt" TO updated_at;

ALTER TABLE inventory_items RENAME COLUMN "UnitPrice" TO unit_price;

ALTER TABLE inventory_items RENAME COLUMN "TenantId" TO tenant_id;

ALTER TABLE inventory_items RENAME COLUMN "QuantityOnHand" TO quantity_on_hand;

ALTER TABLE inventory_items RENAME COLUMN "InboundDocumentId" TO inbound_document_id;

ALTER INDEX "IX_InventoryItems_VendorId" RENAME TO "IX_inventory_items_vendor_id";

ALTER INDEX "IX_InventoryItems_TenantId_Sku" RENAME TO "IX_inventory_items_tenant_id_sku";

ALTER INDEX "IX_InventoryItems_InboundDocumentId" RENAME TO "IX_inventory_items_inbound_document_id";

ALTER TABLE inventory_items ALTER COLUMN sku TYPE character varying(128);

ALTER TABLE inventory_items ALTER COLUMN name TYPE character varying(256);

ALTER TABLE inventory_items ALTER COLUMN category TYPE character varying(128);

ALTER TABLE inventory_items ADD container_type character varying(128) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD description character varying(2000) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD disti_sku character varying(256) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD manufacturer character varying(256) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD min_qty integer NOT NULL DEFAULT 0;

ALTER TABLE inventory_items ADD mpn character varying(128) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD price_tiers_json text NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD region character varying(128) NOT NULL DEFAULT '';

ALTER TABLE inventory_items ADD stock integer NOT NULL DEFAULT 0;

ALTER TABLE inventory_items ADD CONSTRAINT "PK_inventory_items" PRIMARY KEY (id);

CREATE INDEX "IX_inventory_items_tenant_id_mpn" ON inventory_items (tenant_id, mpn);

ALTER TABLE inventory_items ADD CONSTRAINT "FK_inventory_items_InboundDocuments_inbound_document_id" FOREIGN KEY (inbound_document_id) REFERENCES "InboundDocuments" ("Id") ON DELETE SET NULL;

ALTER TABLE inventory_items ADD CONSTRAINT "FK_inventory_items_Vendors_vendor_id" FOREIGN KEY (vendor_id) REFERENCES "Vendors" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260805121310_AlignInventorySchemaForFindchips', '10.0.10');

COMMIT;

